#!/usr/bin/env python3
"""
Post a security review summary as a comment on a GitHub pull request.

Usage:
    GH_TOKEN=... python post_pr_comment.py \
        --report /tmp/appsec-report.md \
        --pr 42 \
        --run-url https://github.com/org/repo/actions/runs/123
"""
import argparse
import os
import re
import subprocess
import sys


SEVERITY_ORDER = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', 'INFORMATIONAL']

SEVERITY_EMOJI = {
    'CRITICAL': '🔴',
    'HIGH': '🟠',
    'MEDIUM': '🟡',
    'LOW': '🔵',
    'INFO': '⚪',
    'INFORMATIONAL': '⚪',
}

MERGE_REC_STYLE = {
    'BLOCK': '🚫 **BLOCK**',
    'MERGE WITH ACTION': '⚠️ **MERGE WITH ACTION**',
    'MERGE': '✅ **MERGE**',
}


def _detect_report_type(report_text):
    for prefix, report_type in [
        ('[TM-', 'threat-model'),
        ('[DA-', 'dependency-audit'),
        ('[SS-', 'secrets-scan'),
        ('[IC-', 'iac-review'),
        ('[CI-', 'cicd-audit'),
        ('[AR-', 'api-security'),
        ('[AU-', 'auth-review'),
        ('[CR-', 'code-review'),
    ]:
        if prefix in report_text:
            return report_type
    return 'code-review'


def extract_summary(report_text):
    """Parse the executive summary section of a threatlint report."""
    summary = {
        'risk_level': 'UNKNOWN',
        'merge_recommendation': None,
        'findings_by_severity': {},
        'top_issues': [],
        'report_type': _detect_report_type(report_text),
    }

    # Risk level / Change Risk Level
    m = re.search(r'\*\*(CRITICAL|HIGH|MEDIUM|LOW|CLEAN)\*\*\s*(?:/\s*\*\*(CRITICAL|HIGH|MEDIUM|LOW|CLEAN)\*\*\s*)*\n', report_text)
    if m:
        summary['risk_level'] = m.group(1)

    # Merge recommendation
    m = re.search(r'\*\*(BLOCK|MERGE WITH ACTION|MERGE)\*\*', report_text)
    if m:
        summary['merge_recommendation'] = m.group(1)

    # Finding summary table
    table_pattern = re.compile(
        r'\|\s*(Critical|High|Medium|Low|Informational)\s*\|\s*(\d+)\s*\|\s*(\d+)\s*\|\s*(\d+)\s*\|\s*(\d+)\s*\|',
        re.IGNORECASE,
    )
    for row in table_pattern.finditer(report_text):
        sev = row.group(1).upper()
        count = int(row.group(2))
        if count > 0:
            summary['findings_by_severity'][sev] = {
                'total': count,
                'confirmed': int(row.group(3)),
                'plausible': int(row.group(4)),
                'theoretical': int(row.group(5)),
            }

    # Top issues (bullet points under ### Top Issues or ### Top Immediate Actions)
    top_section = re.search(r'### Top (?:Issues|Immediate Actions)\n+(.*?)(?=\n###|\Z)', report_text, re.DOTALL)
    if top_section:
        for line in top_section.group(1).strip().split('\n'):
            m = re.match(r'\s*[-*]\s*\*\*(\[(?:TM|CR|DA|IC|CI|AR|AU|SS)-\d+\])\*\*\s*(.*)', line)
            if m:
                summary['top_issues'].append({'id': m.group(1), 'detail': m.group(2).strip()})

    return summary


def build_comment(summary, run_url):
    lines = []
    risk = summary['risk_level']
    emoji = SEVERITY_EMOJI.get(risk, '⚪')

    report_type_label = {
        'threat-model': 'Threat Model',
        'code-review': 'Code Review',
        'dependency-audit': 'Dependency Audit',
        'secrets-scan': 'Secrets Scan',
        'iac-review': 'IaC Review',
        'cicd-audit': 'CI/CD Audit',
        'api-security': 'API Security Review',
        'auth-review': 'Auth Review',
    }.get(summary['report_type'], 'Security Review')
    lines.append(f'## {emoji} AppSec {report_type_label}: **{risk}**')
    lines.append('')

    if summary['merge_recommendation']:
        rec = summary['merge_recommendation']
        lines.append(f'**Merge recommendation**: {MERGE_REC_STYLE.get(rec, rec)}')
        lines.append('')

    # Findings table
    findings = summary['findings_by_severity']
    if findings:
        lines.append('| Severity | Total | Confirmed | Plausible | Theoretical |')
        lines.append('|----------|-------|-----------|-----------|-------------|')
        for sev in SEVERITY_ORDER:
            if sev in findings:
                f = findings[sev]
                em = SEVERITY_EMOJI.get(sev, '')
                lines.append(f'| {em} {sev.title()} | {f["total"]} | {f["confirmed"]} | {f["plausible"]} | {f["theoretical"]} |')
        lines.append('')

    # Top issues
    if summary['top_issues']:
        lines.append('**Top issues:**')
        for issue in summary['top_issues'][:5]:
            lines.append(f'- **{issue["id"]}** {issue["detail"]}')
        lines.append('')

    lines.append(f'[View full report in workflow run]({run_url})')
    lines.append('')
    lines.append('<sub>Generated by [threatlint](https://github.com/h0p3sf4ll/threatlint)</sub>')

    return '\n'.join(lines)


def post_comment(pr_number, comment_body):
    token = os.environ.get('GH_TOKEN') or os.environ.get('GITHUB_TOKEN')
    if not token:
        print('ERROR: GH_TOKEN or GITHUB_TOKEN must be set.', file=sys.stderr)
        sys.exit(1)

    result = subprocess.run(
        ['gh', 'pr', 'comment', str(pr_number), '--body', comment_body],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f'ERROR posting PR comment: {result.stderr}', file=sys.stderr)
        sys.exit(1)
    print(f'PR comment posted to PR #{pr_number}.', flush=True)


def main():
    parser = argparse.ArgumentParser(description='Post AppSec summary as PR comment')
    parser.add_argument('--report', required=True, help='Path to Markdown report')
    parser.add_argument('--pr', required=True, type=int, help='Pull request number')
    parser.add_argument('--run-url', required=True, help='GitHub Actions run URL')
    args = parser.parse_args()

    try:
        with open(args.report) as f:
            report_text = f.read()
    except OSError as e:
        print(f'ERROR: Cannot read report: {e}', file=sys.stderr)
        sys.exit(1)

    summary = extract_summary(report_text)
    comment = build_comment(summary, args.run_url)
    post_comment(args.pr, comment)


if __name__ == '__main__':
    main()
